# Generated by Django 4.0.5 on 2022-06-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_poll_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='choicetext',
        ),
    ]
