# Generated by Django 4.0.5 on 2022-06-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_choicetext_choice_choice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
