# Generated by Django 4.0.5 on 2022-06-25 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0005_poll_total_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='users_voted',
            field=models.ManyToManyField(related_name='usersvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
