# Generated by Django 4.0.5 on 2022-06-25 14:24

from django.conf import settings
from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0006_poll_users_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='users_voted',
            field=models.ManyToManyField(default=polls.models.returnNone, related_name='usersvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
