# Generated by Django 4.0.5 on 2022-06-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_poll_max_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='max_options',
            new_name='no_of_options_to_be_selected',
        ),
    ]
