# Generated by Django 4.0.5 on 2022-06-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_rename_max_options_poll_no_of_options_to_be_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='anonymous_poll',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
