# Generated by Django 4.0.5 on 2022-06-26 19:01

from django.conf import settings
from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0012_rename_public_poll_public_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='voted_by',
            field=models.ManyToManyField(default=polls.models.returnNone, to=settings.AUTH_USER_MODEL),
        ),
    ]
